services:
  mongodb:
    image: mongo:7
    container_name: silver-mongodb
    ports:
      - "27017:27017"
    volumes:
      - silver_mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: silver_db

volumes:
  silver_mongodb_data:
